---
# tasks file for spf
- name: "packages"
  package:
    name: '{{ item }}'
  with_items:
    - '{{ spf_packages }}'
  tags:
    - spf
    - packages

- name: "policyd-spf.conf"
  template:
    src: 'policyd-spf.conf.j2'
    dest: '{{ spf_policyd_config_file }}'
  notify: restart postfix
  tags:
    - spf
    - conf
...
