---
# tasks file for spf
- name: package
  package:
    name: '{{ spf_packages }}'
  tags:
    - spf
    - package

- name: "policyd-spf.conf"
  template:
    src: 'policyd-spf.conf.j2'
    dest: '{{ spf_policyd_config_file }}'
  notify: restart postfix
  tags:
    - spf
    - conf
...
